# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gismo < Formula
  desc "Gismo - Real-time linting feedback for AI code editors"
  homepage "https://gismo.run"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jrossi/gismo/releases/download/v0.4.0/gismo_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "10bc640c43d6cab6309f04a3af14b8744ca5a9618b64c5c853126b4c7e7ae3a3"

      def install
        bin.install "gismo"
        bin.install "gismo-init"
        bin.install "gismo-show"
        bin.install "gismo-registry"
        bin.install "gismo-package"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jrossi/gismo/releases/download/v0.4.0/gismo_0.4.0_Darwin_arm64.tar.gz"
      sha256 "54c704820a680b1cccbdeacf85cebff4a73ea055b24a8976168db41566d5eea3"

      def install
        bin.install "gismo"
        bin.install "gismo-init"
        bin.install "gismo-show"
        bin.install "gismo-registry"
        bin.install "gismo-package"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/gismo/releases/download/v0.4.0/gismo_0.4.0_Linux_x86_64.tar.gz"
      sha256 "93d19bf328cbbfcbf142dfb0d1e12a34bfb05f07b07d6ae4d0883d1e33003927"
      def install
        bin.install "gismo"
        bin.install "gismo-init"
        bin.install "gismo-show"
        bin.install "gismo-registry"
        bin.install "gismo-package"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/gismo/releases/download/v0.4.0/gismo_0.4.0_Linux_arm64.tar.gz"
      sha256 "fc73cef7c880ac942cc3a04ead315af8ca9a6305719312a4e9d7d2d24de0f1ea"
      def install
        bin.install "gismo"
        bin.install "gismo-init"
        bin.install "gismo-show"
        bin.install "gismo-registry"
        bin.install "gismo-package"
      end
    end
  end

  test do
    system "#{bin}/gismo", "--version"
  end
end
