# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gismo < Formula
  desc "Gismo - Real-time linting feedback for AI code editors"
  homepage "https://gismo.run"
  version "0.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jrossi/gismo/releases/download/v0.4.2/gismo_0.4.2_Darwin_x86_64.tar.gz"
      sha256 "f89fe8a81b02f229006cd0614fdc50368a35e1e8b2c62e64707d4696e6426567"

      def install
        bin.install "gismo"
        bin.install "gismo-init"
        bin.install "gismo-show"
        bin.install "gismo-registry"
        bin.install "gismo-package"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jrossi/gismo/releases/download/v0.4.2/gismo_0.4.2_Darwin_arm64.tar.gz"
      sha256 "947f5b333aa5442e102845f7047931fafc6ce85f619db34a8499bf16f99b1d4a"

      def install
        bin.install "gismo"
        bin.install "gismo-init"
        bin.install "gismo-show"
        bin.install "gismo-registry"
        bin.install "gismo-package"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/gismo/releases/download/v0.4.2/gismo_0.4.2_Linux_x86_64.tar.gz"
      sha256 "d82d4f8990ca9258273ab3c58c01e45deba6f42d4dede9f4ac26b6388c785130"
      def install
        bin.install "gismo"
        bin.install "gismo-init"
        bin.install "gismo-show"
        bin.install "gismo-registry"
        bin.install "gismo-package"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jrossi/gismo/releases/download/v0.4.2/gismo_0.4.2_Linux_arm64.tar.gz"
      sha256 "febee12a274cb6e7c8715e5dadf3e42f69be6fb2340f64049e50a27880f753cc"
      def install
        bin.install "gismo"
        bin.install "gismo-init"
        bin.install "gismo-show"
        bin.install "gismo-registry"
        bin.install "gismo-package"
      end
    end
  end

  test do
    system "#{bin}/gismo", "--version"
  end
end
