// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type CodeChunk struct {
	ID           int64          `json:"id"`
	ProjectID    int64          `json:"project_id"`
	FilePath     string         `json:"file_path"`
	AbsolutePath string         `json:"absolute_path"`
	Content      string         `json:"content"`
	ChunkType    string         `json:"chunk_type"`
	Language     string         `json:"language"`
	StartLine    int64          `json:"start_line"`
	EndLine      int64          `json:"end_line"`
	Embedding    []byte         `json:"embedding"`
	Metadata     sql.NullString `json:"metadata"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type IndexStat struct {
	ID            int64        `json:"id"`
	TotalChunks   int64        `json:"total_chunks"`
	TotalFiles    int64        `json:"total_files"`
	Languages     string       `json:"languages"`
	LastIndexedAt sql.NullTime `json:"last_indexed_at"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type Project struct {
	ID            int64          `json:"id"`
	ProjectName   string         `json:"project_name"`
	ProjectPath   string         `json:"project_path"`
	Description   sql.NullString `json:"description"`
	LastIndexedAt sql.NullTime   `json:"last_indexed_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type SearchHistory struct {
	ID              int64          `json:"id"`
	Query           string         `json:"query"`
	ResultCount     int64          `json:"result_count"`
	Filters         sql.NullString `json:"filters"`
	ExecutionTimeMs sql.NullInt64  `json:"execution_time_ms"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}
