// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteCodeChunksByFilePath = `-- name: DeleteCodeChunksByFilePath :exec
DELETE FROM code_chunks WHERE project_id = ? AND file_path = ?
`

type DeleteCodeChunksByFilePathParams struct {
	ProjectID int64  `json:"project_id"`
	FilePath  string `json:"file_path"`
}

func (q *Queries) DeleteCodeChunksByFilePath(ctx context.Context, arg DeleteCodeChunksByFilePathParams) error {
	_, err := q.db.ExecContext(ctx, deleteCodeChunksByFilePath, arg.ProjectID, arg.FilePath)
	return err
}

const deleteCodeChunksByProject = `-- name: DeleteCodeChunksByProject :exec
DELETE FROM code_chunks WHERE project_id = ?
`

func (q *Queries) DeleteCodeChunksByProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCodeChunksByProject, projectID)
	return err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT id, project_name, project_path, description, last_indexed_at, created_at, updated_at FROM projects 
ORDER BY project_name
`

func (q *Queries) GetAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.ProjectPath,
			&i.Description,
			&i.LastIndexedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChunkTypeStats = `-- name: GetChunkTypeStats :many
SELECT chunk_type, COUNT(*) as count 
FROM code_chunks 
WHERE project_id = ?
GROUP BY chunk_type 
ORDER BY count DESC
`

type GetChunkTypeStatsRow struct {
	ChunkType string `json:"chunk_type"`
	Count     int64  `json:"count"`
}

func (q *Queries) GetChunkTypeStats(ctx context.Context, projectID int64) ([]GetChunkTypeStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getChunkTypeStats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChunkTypeStatsRow{}
	for rows.Next() {
		var i GetChunkTypeStatsRow
		if err := rows.Scan(&i.ChunkType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCodeChunkByID = `-- name: GetCodeChunkByID :one
SELECT id, project_id, file_path, absolute_path, content, chunk_type, language, start_line, end_line, embedding, metadata, created_at, updated_at FROM code_chunks WHERE id = ?
`

func (q *Queries) GetCodeChunkByID(ctx context.Context, id int64) (CodeChunk, error) {
	row := q.db.QueryRowContext(ctx, getCodeChunkByID, id)
	var i CodeChunk
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FilePath,
		&i.AbsolutePath,
		&i.Content,
		&i.ChunkType,
		&i.Language,
		&i.StartLine,
		&i.EndLine,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCodeChunksByFilePath = `-- name: GetCodeChunksByFilePath :many
SELECT id, project_id, file_path, absolute_path, content, chunk_type, language, start_line, end_line, embedding, metadata, created_at, updated_at FROM code_chunks 
WHERE project_id = ? AND file_path = ? 
ORDER BY start_line
`

type GetCodeChunksByFilePathParams struct {
	ProjectID int64  `json:"project_id"`
	FilePath  string `json:"file_path"`
}

func (q *Queries) GetCodeChunksByFilePath(ctx context.Context, arg GetCodeChunksByFilePathParams) ([]CodeChunk, error) {
	rows, err := q.db.QueryContext(ctx, getCodeChunksByFilePath, arg.ProjectID, arg.FilePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeChunk{}
	for rows.Next() {
		var i CodeChunk
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FilePath,
			&i.AbsolutePath,
			&i.Content,
			&i.ChunkType,
			&i.Language,
			&i.StartLine,
			&i.EndLine,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileCount = `-- name: GetFileCount :one
SELECT COUNT(DISTINCT file_path) as count FROM code_chunks WHERE project_id = ?
`

func (q *Queries) GetFileCount(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFileCount, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLanguageStats = `-- name: GetLanguageStats :many
SELECT language, COUNT(*) as count 
FROM code_chunks 
WHERE project_id = ?
GROUP BY language 
ORDER BY count DESC
`

type GetLanguageStatsRow struct {
	Language string `json:"language"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetLanguageStats(ctx context.Context, projectID int64) ([]GetLanguageStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLanguageStats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLanguageStatsRow{}
	for rows.Next() {
		var i GetLanguageStatsRow
		if err := rows.Scan(&i.Language, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestIndexStats = `-- name: GetLatestIndexStats :one
SELECT id, total_chunks, total_files, languages, last_indexed_at, created_at, updated_at FROM index_stats 
ORDER BY created_at DESC 
LIMIT 1
`

func (q *Queries) GetLatestIndexStats(ctx context.Context) (IndexStat, error) {
	row := q.db.QueryRowContext(ctx, getLatestIndexStats)
	var i IndexStat
	err := row.Scan(
		&i.ID,
		&i.TotalChunks,
		&i.TotalFiles,
		&i.Languages,
		&i.LastIndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, project_name, project_path, description, last_indexed_at, created_at, updated_at FROM projects WHERE project_name = ?
`

func (q *Queries) GetProjectByName(ctx context.Context, projectName string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByName, projectName)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.ProjectPath,
		&i.Description,
		&i.LastIndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByPath = `-- name: GetProjectByPath :one
SELECT id, project_name, project_path, description, last_indexed_at, created_at, updated_at FROM projects WHERE project_path = ?
`

func (q *Queries) GetProjectByPath(ctx context.Context, projectPath string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByPath, projectPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.ProjectPath,
		&i.Description,
		&i.LastIndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentSearches = `-- name: GetRecentSearches :many
SELECT id, "query", result_count, filters, execution_time_ms, created_at FROM search_history 
ORDER BY created_at DESC 
LIMIT ?
`

func (q *Queries) GetRecentSearches(ctx context.Context, limit int64) ([]SearchHistory, error) {
	rows, err := q.db.QueryContext(ctx, getRecentSearches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchHistory{}
	for rows.Next() {
		var i SearchHistory
		if err := rows.Scan(
			&i.ID,
			&i.Query,
			&i.ResultCount,
			&i.Filters,
			&i.ExecutionTimeMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalChunksCount = `-- name: GetTotalChunksCount :one
SELECT COUNT(*) as count FROM code_chunks WHERE project_id = ?
`

func (q *Queries) GetTotalChunksCount(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalChunksCount, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertCodeChunk = `-- name: InsertCodeChunk :one
INSERT INTO code_chunks (
    project_id, file_path, absolute_path, content, chunk_type, language, 
    start_line, end_line, embedding, metadata
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, vector(?), ?
) RETURNING id, project_id, file_path, absolute_path, content, chunk_type, language, start_line, end_line, embedding, metadata, created_at, updated_at
`

type InsertCodeChunkParams struct {
	ProjectID    int64          `json:"project_id"`
	FilePath     string         `json:"file_path"`
	AbsolutePath string         `json:"absolute_path"`
	Content      string         `json:"content"`
	ChunkType    string         `json:"chunk_type"`
	Language     string         `json:"language"`
	StartLine    int64          `json:"start_line"`
	EndLine      int64          `json:"end_line"`
	Vector       interface{}    `json:"vector"`
	Metadata     sql.NullString `json:"metadata"`
}

func (q *Queries) InsertCodeChunk(ctx context.Context, arg InsertCodeChunkParams) (CodeChunk, error) {
	row := q.db.QueryRowContext(ctx, insertCodeChunk,
		arg.ProjectID,
		arg.FilePath,
		arg.AbsolutePath,
		arg.Content,
		arg.ChunkType,
		arg.Language,
		arg.StartLine,
		arg.EndLine,
		arg.Vector,
		arg.Metadata,
	)
	var i CodeChunk
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FilePath,
		&i.AbsolutePath,
		&i.Content,
		&i.ChunkType,
		&i.Language,
		&i.StartLine,
		&i.EndLine,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCodeChunkWithoutEmbedding = `-- name: InsertCodeChunkWithoutEmbedding :one
INSERT INTO code_chunks (
    project_id, file_path, absolute_path, content, chunk_type, language, 
    start_line, end_line, metadata
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, project_id, file_path, absolute_path, content, chunk_type, language, start_line, end_line, embedding, metadata, created_at, updated_at
`

type InsertCodeChunkWithoutEmbeddingParams struct {
	ProjectID    int64          `json:"project_id"`
	FilePath     string         `json:"file_path"`
	AbsolutePath string         `json:"absolute_path"`
	Content      string         `json:"content"`
	ChunkType    string         `json:"chunk_type"`
	Language     string         `json:"language"`
	StartLine    int64          `json:"start_line"`
	EndLine      int64          `json:"end_line"`
	Metadata     sql.NullString `json:"metadata"`
}

func (q *Queries) InsertCodeChunkWithoutEmbedding(ctx context.Context, arg InsertCodeChunkWithoutEmbeddingParams) (CodeChunk, error) {
	row := q.db.QueryRowContext(ctx, insertCodeChunkWithoutEmbedding,
		arg.ProjectID,
		arg.FilePath,
		arg.AbsolutePath,
		arg.Content,
		arg.ChunkType,
		arg.Language,
		arg.StartLine,
		arg.EndLine,
		arg.Metadata,
	)
	var i CodeChunk
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FilePath,
		&i.AbsolutePath,
		&i.Content,
		&i.ChunkType,
		&i.Language,
		&i.StartLine,
		&i.EndLine,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (
    project_name, project_path, description
) VALUES (
    ?, ?, ?
) ON CONFLICT(project_name) DO UPDATE SET
    updated_at = CURRENT_TIMESTAMP
RETURNING id, project_name, project_path, description, last_indexed_at, created_at, updated_at
`

type InsertProjectParams struct {
	ProjectName string         `json:"project_name"`
	ProjectPath string         `json:"project_path"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, insertProject, arg.ProjectName, arg.ProjectPath, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.ProjectPath,
		&i.Description,
		&i.LastIndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSearchHistory = `-- name: InsertSearchHistory :one
INSERT INTO search_history (
    query, result_count, filters, execution_time_ms
) VALUES (
    ?, ?, ?, ?
) RETURNING id, "query", result_count, filters, execution_time_ms, created_at
`

type InsertSearchHistoryParams struct {
	Query           string         `json:"query"`
	ResultCount     int64          `json:"result_count"`
	Filters         sql.NullString `json:"filters"`
	ExecutionTimeMs sql.NullInt64  `json:"execution_time_ms"`
}

func (q *Queries) InsertSearchHistory(ctx context.Context, arg InsertSearchHistoryParams) (SearchHistory, error) {
	row := q.db.QueryRowContext(ctx, insertSearchHistory,
		arg.Query,
		arg.ResultCount,
		arg.Filters,
		arg.ExecutionTimeMs,
	)
	var i SearchHistory
	err := row.Scan(
		&i.ID,
		&i.Query,
		&i.ResultCount,
		&i.Filters,
		&i.ExecutionTimeMs,
		&i.CreatedAt,
	)
	return i, err
}

const searchCodeChunksByLanguage = `-- name: SearchCodeChunksByLanguage :many
SELECT cc.id, cc.project_id, cc.file_path, cc.absolute_path, cc.content, cc.chunk_type, cc.language, cc.start_line, cc.end_line, cc.embedding, cc.metadata, cc.created_at, cc.updated_at, p.project_name, p.project_path 
FROM code_chunks cc
JOIN projects p ON cc.project_id = p.id
WHERE cc.project_id = ? AND cc.language = ? 
ORDER BY cc.file_path, cc.start_line
LIMIT ?
`

type SearchCodeChunksByLanguageParams struct {
	ProjectID int64  `json:"project_id"`
	Language  string `json:"language"`
	Limit     int64  `json:"limit"`
}

type SearchCodeChunksByLanguageRow struct {
	ID           int64          `json:"id"`
	ProjectID    int64          `json:"project_id"`
	FilePath     string         `json:"file_path"`
	AbsolutePath string         `json:"absolute_path"`
	Content      string         `json:"content"`
	ChunkType    string         `json:"chunk_type"`
	Language     string         `json:"language"`
	StartLine    int64          `json:"start_line"`
	EndLine      int64          `json:"end_line"`
	Embedding    []byte         `json:"embedding"`
	Metadata     sql.NullString `json:"metadata"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	ProjectName  string         `json:"project_name"`
	ProjectPath  string         `json:"project_path"`
}

func (q *Queries) SearchCodeChunksByLanguage(ctx context.Context, arg SearchCodeChunksByLanguageParams) ([]SearchCodeChunksByLanguageRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCodeChunksByLanguage, arg.ProjectID, arg.Language, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCodeChunksByLanguageRow{}
	for rows.Next() {
		var i SearchCodeChunksByLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FilePath,
			&i.AbsolutePath,
			&i.Content,
			&i.ChunkType,
			&i.Language,
			&i.StartLine,
			&i.EndLine,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.ProjectPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCodeChunksByType = `-- name: SearchCodeChunksByType :many
SELECT cc.id, cc.project_id, cc.file_path, cc.absolute_path, cc.content, cc.chunk_type, cc.language, cc.start_line, cc.end_line, cc.embedding, cc.metadata, cc.created_at, cc.updated_at, p.project_name, p.project_path 
FROM code_chunks cc
JOIN projects p ON cc.project_id = p.id
WHERE cc.project_id = ? AND cc.chunk_type = ? 
ORDER BY cc.file_path, cc.start_line
LIMIT ?
`

type SearchCodeChunksByTypeParams struct {
	ProjectID int64  `json:"project_id"`
	ChunkType string `json:"chunk_type"`
	Limit     int64  `json:"limit"`
}

type SearchCodeChunksByTypeRow struct {
	ID           int64          `json:"id"`
	ProjectID    int64          `json:"project_id"`
	FilePath     string         `json:"file_path"`
	AbsolutePath string         `json:"absolute_path"`
	Content      string         `json:"content"`
	ChunkType    string         `json:"chunk_type"`
	Language     string         `json:"language"`
	StartLine    int64          `json:"start_line"`
	EndLine      int64          `json:"end_line"`
	Embedding    []byte         `json:"embedding"`
	Metadata     sql.NullString `json:"metadata"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	ProjectName  string         `json:"project_name"`
	ProjectPath  string         `json:"project_path"`
}

func (q *Queries) SearchCodeChunksByType(ctx context.Context, arg SearchCodeChunksByTypeParams) ([]SearchCodeChunksByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCodeChunksByType, arg.ProjectID, arg.ChunkType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCodeChunksByTypeRow{}
	for rows.Next() {
		var i SearchCodeChunksByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FilePath,
			&i.AbsolutePath,
			&i.Content,
			&i.ChunkType,
			&i.Language,
			&i.StartLine,
			&i.EndLine,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.ProjectPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCodeChunkEmbedding = `-- name: UpdateCodeChunkEmbedding :exec
UPDATE code_chunks 
SET embedding = vector(?), updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCodeChunkEmbeddingParams struct {
	Vector interface{} `json:"vector"`
	ID     int64       `json:"id"`
}

func (q *Queries) UpdateCodeChunkEmbedding(ctx context.Context, arg UpdateCodeChunkEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, updateCodeChunkEmbedding, arg.Vector, arg.ID)
	return err
}

const updateIndexStats = `-- name: UpdateIndexStats :one
INSERT INTO index_stats (
    total_chunks, total_files, languages, last_indexed_at
) VALUES (
    ?, ?, ?, CURRENT_TIMESTAMP
) RETURNING id, total_chunks, total_files, languages, last_indexed_at, created_at, updated_at
`

type UpdateIndexStatsParams struct {
	TotalChunks int64  `json:"total_chunks"`
	TotalFiles  int64  `json:"total_files"`
	Languages   string `json:"languages"`
}

func (q *Queries) UpdateIndexStats(ctx context.Context, arg UpdateIndexStatsParams) (IndexStat, error) {
	row := q.db.QueryRowContext(ctx, updateIndexStats, arg.TotalChunks, arg.TotalFiles, arg.Languages)
	var i IndexStat
	err := row.Scan(
		&i.ID,
		&i.TotalChunks,
		&i.TotalFiles,
		&i.Languages,
		&i.LastIndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectIndexTime = `-- name: UpdateProjectIndexTime :exec
UPDATE projects 
SET last_indexed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateProjectIndexTime(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateProjectIndexTime, id)
	return err
}
