// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	DeleteCodeChunksByFilePath(ctx context.Context, arg DeleteCodeChunksByFilePathParams) error
	DeleteCodeChunksByProject(ctx context.Context, projectID int64) error
	GetAllProjects(ctx context.Context) ([]Project, error)
	GetChunkTypeStats(ctx context.Context, projectID int64) ([]GetChunkTypeStatsRow, error)
	GetCodeChunkByID(ctx context.Context, id int64) (CodeChunk, error)
	GetCodeChunksByFilePath(ctx context.Context, arg GetCodeChunksByFilePathParams) ([]CodeChunk, error)
	GetFileCount(ctx context.Context, projectID int64) (int64, error)
	GetLanguageStats(ctx context.Context, projectID int64) ([]GetLanguageStatsRow, error)
	GetLatestIndexStats(ctx context.Context) (IndexStat, error)
	GetProjectByName(ctx context.Context, projectName string) (Project, error)
	GetProjectByPath(ctx context.Context, projectPath string) (Project, error)
	GetRecentSearches(ctx context.Context, limit int64) ([]SearchHistory, error)
	GetTotalChunksCount(ctx context.Context, projectID int64) (int64, error)
	InsertCodeChunk(ctx context.Context, arg InsertCodeChunkParams) (CodeChunk, error)
	InsertCodeChunkWithoutEmbedding(ctx context.Context, arg InsertCodeChunkWithoutEmbeddingParams) (CodeChunk, error)
	InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error)
	InsertSearchHistory(ctx context.Context, arg InsertSearchHistoryParams) (SearchHistory, error)
	SearchCodeChunksByLanguage(ctx context.Context, arg SearchCodeChunksByLanguageParams) ([]SearchCodeChunksByLanguageRow, error)
	SearchCodeChunksByType(ctx context.Context, arg SearchCodeChunksByTypeParams) ([]SearchCodeChunksByTypeRow, error)
	UpdateCodeChunkEmbedding(ctx context.Context, arg UpdateCodeChunkEmbeddingParams) error
	UpdateIndexStats(ctx context.Context, arg UpdateIndexStatsParams) (IndexStat, error)
	UpdateProjectIndexTime(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
